Add linter

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -45,6 +45,20 @@ else
    echo "$(tput setaf 1)* No$(tput sgr 0)"
 fi
 
+npm run lint >/dev/null 2>/dev/null
+linted=$?
+
+echo $(tput setaf 3)* Linter Passes?$(tput sgr 0)
+
+if [ $linted -eq 0 ]
+then
+   echo "$(tput setaf 2)* Yes$(tput sgr 0)"
+else
+   echo "$(tput setaf 1)* No$(tput sgr 0)"
+    echo "$(tput setaf 1)Please run 'npm run lint' to view linter errors.$(tput sgr 0)"
+    echo ""
+fi
+
 npm run pretty-check >/dev/null 2>/dev/null
 formatted=$?
 
@@ -96,6 +110,12 @@ elif [ $circDep -ne 0 ]
 then
    echo "$(tput setaf 1)... done.$(tput sgr 0)"
    echo "$(tput setaf 1)CANCELLING commit due to CIRCULAR-DEPENDENCIES IN CODE.$(tput sgr 0)"
+   echo ""
+   exit 1
+elif [ $linted -ne 0 ]
+then
+   echo "$(tput setaf 1)... done.$(tput sgr 0)"
+   echo "$(tput setaf 1)CANCELLING commit due to LINTER ERRORS.$(tput sgr 0)"
    echo ""
    exit 1
 elif [ $formatted -ne 0 ]
